"""hostapd.conf templating for the phone-facing AP radio (Phase 6).

Renders the hostapd config from the deployment-wide SSID/passphrase
(deployment_config.py) so the identity is never hand-edited into
/etc/hostapd. scripts/setup_hostapd.sh runs `python3 -m
node.wifi_ap.hostapd_config` and installs the output.

Channel planning: the AP lives on 2.4 GHz (channel 6 by default) so it never
shares a band with the backhaul radio's 5745 MHz (channel 149, 5 GHz) mesh —
the two-radios-must-not-interfere rule from the WiFi Mesh Add-On. The
per-node channel is overridable for venue RF planning; the SSID/passphrase
deliberately are not.
"""
import os

from node.wifi_ap.deployment_config import (
    WifiDeploymentConfig,
    load_deployment_config,
)

# Pi onboard radio. BLE serving uses the Bluetooth radio and the backhaul
# owns wlan1 (see node/backhaul/radio_config.py), so wlan0 is free for AP
# duty. Must match scripts/setup_hostapd.sh.
AP_IFACE = os.environ.get("MESHLINK_AP_IFACE", "wlan0")
AP_CHANNEL = int(os.environ.get("MESHLINK_AP_CHANNEL", "6"))


def render_hostapd_conf(
    config: WifiDeploymentConfig,
    iface: str = AP_IFACE,
    channel: int = AP_CHANNEL,
) -> str:
    if not 1 <= channel <= 13:  # 2.4 GHz only — 5 GHz belongs to the backhaul
        raise ValueError(f"AP channel must be 1-13 (2.4 GHz), got {channel}")
    return f"""\
# Generated by node/wifi_ap/hostapd_config.py — do not hand-edit.
# SSID/passphrase come from the deployment-wide config; see
# docs/wifi-ap-deployment.md.
interface={iface}
driver=nl80211

ssid={config.ssid}
hw_mode=g
channel={channel}
ieee80211n=1
wmm_enabled=1

auth_algs=1
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
wpa_passphrase={config.passphrase}

# Roaming assists (WiFi Mesh Add-On §2.4): 802.11k neighbor reports and
# 802.11v BSS transition hints help phones hand off between nodes sooner.
# 802.11r fast transition is deferred — it needs cross-node key material.
rrm_neighbor_report=1
bss_transition=1
"""


if __name__ == "__main__":
    print(render_hostapd_conf(load_deployment_config()), end="")
