#!/usr/bin/env bash
# hostapd AP-mode configuration for the phone-facing radio (Phase 6).
#
# Puts the node's onboard radio (wlan0 — the backhaul owns wlan1, BLE uses
# the Bluetooth radio) into AP mode broadcasting the deployment-wide SSID, so
# phones can join the mesh over WiFi instead of BLE. This is a closed,
# internet-less network exactly like the backhaul: phones get an IP via DHCP
# but no gateway and no DNS — nothing here routes or NATs anywhere.
#
# The SSID/passphrase are never set in this script: they are rendered from
# the central deployment config (/etc/meshlink/wifi_deployment.conf) by
# node/wifi_ap/hostapd_config.py. Push that file first — see
# docs/wifi-ap-deployment.md.
#
# Idempotent: safe to re-run on every boot.
#
# Run as root from the repo root: sudo scripts/setup_hostapd.sh
set -euo pipefail

IFACE="${MESHLINK_AP_IFACE:-wlan0}"
AP_ADDR="10.78.0.1/24"                 # AP subnet — distinct from the 10.77.0.x backhaul
DHCP_RANGE="10.78.0.50,10.78.0.250,12h"
HOSTAPD_CONF="/etc/hostapd/meshlink.conf"
DNSMASQ_CONF="/etc/dnsmasq.d/meshlink-ap.conf"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

if [[ $EUID -ne 0 ]]; then
    echo "Run as root: sudo scripts/setup_hostapd.sh" >&2
    exit 1
fi

for cmd in hostapd dnsmasq; do
    if ! command -v "$cmd" &>/dev/null; then
        echo "'$cmd' not installed — apt install hostapd dnsmasq" >&2
        exit 1
    fi
done

if ! ip link show "$IFACE" &>/dev/null; then
    echo "AP radio '$IFACE' not found." >&2
    exit 1
fi

# Render hostapd.conf from the deployment config. Fails loudly (with a
# pointer to the deployment procedure) if the config is missing or invalid —
# a node must not invent its own SSID.
cd "$REPO_ROOT"
python3 -m node.wifi_ap.hostapd_config > "${HOSTAPD_CONF}.tmp"
mv "${HOSTAPD_CONF}.tmp" "$HOSTAPD_CONF"
chmod 600 "$HOSTAPD_CONF"   # contains the WPA passphrase

# Keep NetworkManager / wpa_supplicant from fighting hostapd over the radio.
if command -v nmcli &>/dev/null; then
    nmcli device set "$IFACE" managed no 2>/dev/null || true
fi

ip addr flush dev "$IFACE"
ip addr add "$AP_ADDR" dev "$IFACE"
ip link set "$IFACE" up

# DHCP for joining phones. dhcp-option 3/6 left empty = no default gateway,
# no DNS — the OS-level "no internet" verdict is by design (Add-On §3), and
# omitting a gateway keeps any phone from ever trying to route through us.
cat > "$DNSMASQ_CONF" <<EOF
# Generated by scripts/setup_hostapd.sh — MeshLink phone-facing AP DHCP.
interface=$IFACE
bind-interfaces
dhcp-range=$DHCP_RANGE
dhcp-option=3
dhcp-option=6
EOF

# Point the distro hostapd service at our config and (re)start both daemons.
if [[ -f /etc/default/hostapd ]]; then
    sed -i 's|^#\?DAEMON_CONF=.*|DAEMON_CONF="'"$HOSTAPD_CONF"'"|' /etc/default/hostapd
fi
systemctl unmask hostapd 2>/dev/null || true
systemctl enable hostapd dnsmasq &>/dev/null || true
systemctl restart dnsmasq
systemctl restart hostapd

ssid="$(grep '^ssid=' "$HOSTAPD_CONF" | cut -d= -f2-)"
echo "$IFACE serving AP '$ssid' on $AP_ADDR (closed network, no WAN)."
echo "Verify from a phone: join the SSID, then check it gets a 10.78.0.x"
echo "address and cannot reach the internet through it."
